// THIS FILE WAS AUTOMATICALLY GENERATED

/* ------------------------------------------------------------------------ */
/* flag */

static METHOD _String_isASCII(CTX ctx, knh_sfp_t *sfp _RIX)
{
	RETURNb_(String_isASCII((knh_String_t*)sfp[0].o));
}

static METHOD _OutputStream_isAutoFlush(CTX ctx, knh_sfp_t *sfp _RIX)
{
	RETURNb_(OutputStream_isAutoFlush((knh_OutputStream_t*)sfp[0].o));
}

static METHOD _OutputStream_setAutoFlush(CTX ctx, knh_sfp_t *sfp _RIX)
{
	OutputStream_setAutoFlush((knh_OutputStream_t*)sfp[0].o, sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

static METHOD _Context_isDebug(CTX ctx, knh_sfp_t *sfp _RIX)
{
	RETURNb_(CTX_isDebug(((sfp[0].cx)->ctx)));
}

static METHOD _Context_setDebug(CTX ctx, knh_sfp_t *sfp _RIX)
{
	CTX_setDebug(((sfp[0].cx)->ctx), sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

/* ------------------------------------------------------------------------ */
/* data */

static const char * StringData0[] = {
	"", /* TS_EMPTY */
	"\t", /* TS_TAB */
	"1", /* TS_ONE */
	""K_OSLINEFEED"", /* TS_EOL */
	"BEGIN", /* TS_BEGIN */
	"END", /* TS_END */
	"true", /* TS_true */
	"false", /* TS_false */
	"null", /* TS_null */
	"void", /* TS_void */
	"main", /* TS_main */
	""K_ENCODING"", /* TS_ENCODING */
	"/dev/null", /* TS_DEVNULL */
	"/dev/stdin", /* TS_DEVSTDIN */
	"/dev/stderr", /* TS_DEVSTDERR */
	"/dev/stdout", /* TS_DEVSTDOUT */
	"@label", /* TS_ATlabel */
	"Assertion!!", /* TS_AssertionException */
	"(", /* TS_LP */
	")", /* TS_RP */
	"{", /* TS_LB */
	"}", /* TS_RB */
	"[", /* TS_LS */
	"]", /* TS_RS */
	NULL
};

static knh_data_t StructData0[] = {
	DATA_STRUCT0, CLASS_Tvoid, _DATA(&TvoidDef), CFLAG_Tvoid,
	DATA_STRUCT0, CLASS_Tvar, _DATA(&TvarDef), CFLAG_Tvar,
	DATA_STRUCT0, CLASS_Object, _DATA(&ObjectDef), CFLAG_Object,
	DATA_STRUCT0, CLASS_Boolean, _DATA(&BooleanDef), CFLAG_Boolean,
	DATA_STRUCT0, CLASS_Number, _DATA(&NumberDef), CFLAG_Number,
	DATA_STRUCT0, CLASS_Int, _DATA(&IntDef), CFLAG_Int,
	DATA_STRUCT0, CLASS_Float, _DATA(&FloatDef), CFLAG_Float,
	DATA_STRUCT0, CLASS_String, _DATA(&StringDef), CFLAG_String,
	DATA_STRUCT0, CLASS_Bytes, _DATA(&BytesDef), CFLAG_Bytes,
	DATA_STRUCT0, CLASS_BytesIm, _DATA(&BytesImDef), CFLAG_BytesIm,
	DATA_STRUCT0, CLASS_Iterator, _DATA(&IteratorDef), CFLAG_Iterator,
	DATA_STRUCT0, CLASS_Tuple, _DATA(&TupleDef), CFLAG_Tuple,
	DATA_STRUCT0, CLASS_Range, _DATA(&RangeDef), CFLAG_Range,
	DATA_STRUCT0, CLASS_Array, _DATA(&ArrayDef), CFLAG_Array,
	DATA_STRUCT0, CLASS_ArrayIm, _DATA(&ArrayImDef), CFLAG_ArrayIm,
	DATA_STRUCT0, CLASS_Map, _DATA(&MapDef), CFLAG_Map,
	DATA_STRUCT0, CLASS_MapIm, _DATA(&MapImDef), CFLAG_MapIm,
	DATA_STRUCT0, CLASS_Class, _DATA(&ClassDef), CFLAG_Class,
	DATA_STRUCT0, CLASS_ParamArray, _DATA(&ParamArrayDef), CFLAG_ParamArray,
	DATA_STRUCT0, CLASS_Method, _DATA(&MethodDef), CFLAG_Method,
	DATA_STRUCT0, CLASS_TypeMap, _DATA(&TypeMapDef), CFLAG_TypeMap,
	DATA_STRUCT0, CLASS_Func, _DATA(&FuncDef), CFLAG_Func,
	DATA_STRUCT0, CLASS_Thunk, _DATA(&ThunkDef), CFLAG_Thunk,
	DATA_STRUCT0, CLASS_Exception, _DATA(&ExceptionDef), CFLAG_Exception,
	DATA_STRUCT0, CLASS_ExceptionHandler, _DATA(&ExceptionHandlerDef), CFLAG_ExceptionHandler,
	DATA_STRUCT0, CLASS_Regex, _DATA(&RegexDef), CFLAG_Regex,
	DATA_STRUCT0, CLASS_Converter, _DATA(&ConverterDef), CFLAG_Converter,
	DATA_STRUCT0, CLASS_StringEncoder, _DATA(&StringEncoderDef), CFLAG_StringEncoder,
	DATA_STRUCT0, CLASS_StringDecoder, _DATA(&StringDecoderDef), CFLAG_StringDecoder,
	DATA_STRUCT0, CLASS_StringConverter, _DATA(&StringConverterDef), CFLAG_StringConverter,
	DATA_STRUCT0, CLASS_Semantics, _DATA(&SemanticsDef), CFLAG_Semantics,
	DATA_STRUCT0, CLASS_InputStream, _DATA(&InputStreamDef), CFLAG_InputStream,
	DATA_STRUCT0, CLASS_OutputStream, _DATA(&OutputStreamDef), CFLAG_OutputStream,
	DATA_STRUCT0, CLASS_Connection, _DATA(&ConnectionDef), CFLAG_Connection,
	DATA_STRUCT0, CLASS_ResultSet, _DATA(&ResultSetDef), CFLAG_ResultSet,
	DATA_STRUCT0, CLASS_NameSpace, _DATA(&NameSpaceDef), CFLAG_NameSpace,
	DATA_STRUCT0, CLASS_Script, _DATA(&ScriptDef), CFLAG_Script,
	DATA_STRUCT0, CLASS_System, _DATA(&SystemDef), CFLAG_System,
	DATA_STRUCT0, CLASS_Context, _DATA(&ContextDef), CFLAG_Context,
	DATA_STRUCT0, CLASS_Monitor, _DATA(&MonitorDef), CFLAG_Monitor,
	DATA_STRUCT0, CLASS_Assurance, _DATA(&AssuranceDef), CFLAG_Assurance,
	DATA_STRUCT0, CLASS_Token, _DATA(&TokenDef), CFLAG_Token,
	DATA_STRUCT0, CLASS_Stmt, _DATA(&StmtDef), CFLAG_Stmt,
	DATA_STRUCT0, CLASS_Gamma, _DATA(&GammaDef), CFLAG_Gamma,
	DATA_STRUCT0, CLASS_BasicBlock, _DATA(&BasicBlockDef), CFLAG_BasicBlock,
	DATA_STRUCT0, CLASS_KonohaCode, _DATA(&KonohaCodeDef), CFLAG_KonohaCode,
	DATA_STRUCT0, CLASS_Immutable, _DATA(&ImmutableDef), CFLAG_Immutable,
	DATA_STRUCT0, CLASS_KindOf, _DATA(&KindOfDef), CFLAG_KindOf,
	DATA_STRUCT0, CLASS_Tdynamic, _DATA(&TdynamicDef), CFLAG_Tdynamic,
	0
};

static knh_data_t ClassData0[] = {
	DATA_CLASS0, CLASS_Tvoid, _DATA("konoha.Tvoid"), CFLAG_Tvoid, CLASS_Tvoid, CLASS_Tvoid, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Tvar, _DATA("konoha.Tvar"), CFLAG_Tvar, CLASS_Tvar, CLASS_Tvoid, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Object, _DATA("konoha.Object"), CFLAG_Object, CLASS_ObjectField, CLASS_Object, 17 + 5 /*0*/,
	DATA_CLASS0, CLASS_Boolean, _DATA("konoha.Boolean"), CFLAG_Boolean, CLASS_Boolean, CLASS_Object, 1 + 4 /*3*/,
	DATA_CLASS0, CLASS_Number, _DATA("konoha.Number"), CFLAG_Number, CLASS_Number, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Int, _DATA("konoha.Int"), CFLAG_Int, CLASS_Int, CLASS_Number, 20 + 10 /*5*/,
	DATA_CLASS0, CLASS_Float, _DATA("konoha.Float"), CFLAG_Float, CLASS_Float, CLASS_Number, 13 + 7 /*5*/,
	DATA_CLASS0, CLASS_String, _DATA("konoha.String"), CFLAG_String, CLASS_String, CLASS_Object, 28 + 0 /*5*/,
	DATA_CLASS0, CLASS_Bytes, _DATA("konoha.Bytes"), CFLAG_Bytes, CLASS_Bytes, CLASS_Object, 13 + 0 /*1*/,
	DATA_CLASS0, CLASS_BytesIm, _DATA("konoha.BytesIm"), CFLAG_BytesIm, CLASS_BytesIm, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Iterator, _DATA("konoha.Iterator"), CFLAG_Iterator, CLASS_Iterator, CLASS_Object, 0 + 0 /*2*/,
	DATA_CLASS0, CLASS_Tuple, _DATA("konoha.Tuple"), CFLAG_Tuple, CLASS_Tuple, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_Range, _DATA("konoha.Range"), CFLAG_Range, CLASS_Range, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_Array, _DATA("konoha.Array"), CFLAG_Array, CLASS_Array, CLASS_Object, 28 + 0 /*2*/,
	DATA_CLASS0, CLASS_ArrayIm, _DATA("konoha.ArrayIm"), CFLAG_ArrayIm, CLASS_ArrayIm, CLASS_Object, 4 + 0 /*0*/,
	DATA_CLASS0, CLASS_Map, _DATA("konoha.Map"), CFLAG_Map, CLASS_Map, CLASS_Object, 9 + 0 /*2*/,
	DATA_CLASS0, CLASS_MapIm, _DATA("konoha.MapIm"), CFLAG_MapIm, CLASS_MapIm, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Class, _DATA("konoha.Class"), CFLAG_Class, CLASS_Class, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_ParamArray, _DATA("konoha.ParamArray"), CFLAG_ParamArray, CLASS_ParamArray, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Method, _DATA("konoha.Method"), CFLAG_Method, CLASS_Method, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_TypeMap, _DATA("konoha.TypeMap"), CFLAG_TypeMap, CLASS_TypeMap, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Func, _DATA("konoha.Func"), CFLAG_Func, CLASS_Func, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_Thunk, _DATA("konoha.Thunk"), CFLAG_Thunk, CLASS_Thunk, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Exception, _DATA("konoha.Exception"), CFLAG_Exception, CLASS_Exception, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_ExceptionHandler, _DATA("konoha.ExceptionHandler"), CFLAG_ExceptionHandler, CLASS_ExceptionHandler, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Regex, _DATA("konoha.Regex"), CFLAG_Regex, CLASS_Regex, CLASS_Object, 2 + 0 /*0*/,
	DATA_CLASS0, CLASS_Converter, _DATA("konoha.Converter"), CFLAG_Converter, CLASS_Converter, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_StringEncoder, _DATA("konoha.StringEncoder"), CFLAG_StringEncoder, CLASS_StringEncoder, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_StringDecoder, _DATA("konoha.StringDecoder"), CFLAG_StringDecoder, CLASS_StringDecoder, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_StringConverter, _DATA("konoha.StringConverter"), CFLAG_StringConverter, CLASS_StringConverter, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Semantics, _DATA("konoha.Semantics"), CFLAG_Semantics, CLASS_Semantics, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_InputStream, _DATA("konoha.InputStream"), CFLAG_InputStream, CLASS_InputStream, CLASS_Object, 7 + 0 /*1*/,
	DATA_CLASS0, CLASS_OutputStream, _DATA("konoha.OutputStream"), CFLAG_OutputStream, CLASS_OutputStream, CLASS_Object, 15 + 0 /*0*/,
	DATA_CLASS0, CLASS_Connection, _DATA("konoha.Connection"), CFLAG_Connection, CLASS_Connection, CLASS_Object, 4 + 0 /*0*/,
	DATA_CLASS0, CLASS_ResultSet, _DATA("konoha.ResultSet"), CFLAG_ResultSet, CLASS_ResultSet, CLASS_Object, 8 + 0 /*0*/,
	DATA_CLASS0, CLASS_NameSpace, _DATA("konoha.NameSpace"), CFLAG_NameSpace, CLASS_NameSpace, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Script, _DATA("konoha.Script"), CFLAG_Script, CLASS_Script, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_System, _DATA("konoha.System"), CFLAG_System, CLASS_System, CLASS_Object, 10 + 0 /*0*/,
	DATA_CLASS0, CLASS_Context, _DATA("konoha.Context"), CFLAG_Context, CLASS_Context, CLASS_Object, 5 + 0 /*0*/,
	DATA_CLASS0, CLASS_Monitor, _DATA("konoha.Monitor"), CFLAG_Monitor, CLASS_Monitor, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Assurance, _DATA("konoha.Assurance"), CFLAG_Assurance, CLASS_Assurance, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS0, CLASS_Token, _DATA("konoha.Token"), CFLAG_Token, CLASS_Token, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Stmt, _DATA("konoha.Stmt"), CFLAG_Stmt, CLASS_Stmt, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Gamma, _DATA("konoha.Gamma"), CFLAG_Gamma, CLASS_Gamma, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_BasicBlock, _DATA("konoha.BasicBlock"), CFLAG_BasicBlock, CLASS_BasicBlock, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_KonohaCode, _DATA("konoha.KonohaCode"), CFLAG_KonohaCode, CLASS_KonohaCode, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Immutable, _DATA("konoha.Immutable"), CFLAG_Immutable, CLASS_Immutable, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_KindOf, _DATA("konoha.KindOf"), CFLAG_KindOf, CLASS_KindOf, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS0, CLASS_Tdynamic, _DATA("konoha.Tdynamic"), CFLAG_Tdynamic, CLASS_dynamic, CLASS_Object, 0 + 0 /*0*/,
	DATA_GENERICS/*RangeInt*/, CLASS_Range, 1, 0, TYPE_Int, FN_,
	DATA_GENERICS/*CmprT1*/, CLASS_Func, 2, 1, TYPE_T1, FN_, TYPE_T1, FN_, TYPE_Int, FN_,
	DATA_GENERICS/*T1ITR*/, CLASS_Iterator, 1, 0, TYPE_T1, FN_,
	DATA_GENERICS/*T1ARRAY*/, CLASS_Array, 1, 0, TYPE_T1, FN_,
	DATA_GENERICS/*StringARRAY*/, CLASS_Array, 1, 0, TYPE_String, FN_,
	DATA_GENERICS/*StringITR*/, CLASS_Iterator, 1, 0, TYPE_String, FN_,
	DATA_EXPT, _DATA("Exception"), 0, EBI_Exception, EBI_Exception, 
	DATA_EXPT, _DATA("Fatal"), 0, EBI_Fatal, EBI_Exception, 
	DATA_EXPT, _DATA("System"), 0, EBI_System, EBI_Exception, 
	DATA_EXPT, _DATA("Security"), 0, EBI_Security, EBI_Exception, 
	DATA_EXPT, _DATA("SourceCode"), 0, EBI_SourceCode, EBI_Exception, 
	DATA_EXPT, _DATA("Type"), 0, EBI_Type, EBI_Exception, 
	DATA_EXPT, _DATA("Assertion"), 0, EBI_Assertion, EBI_Exception, 
	0
};

static knh_FieldNameData0_t FieldNameData0[] = {
	{"", FN_},
	{"2", FN_2},
	{"3", FN_3},
	{"4", FN_4},
	{"abstract", FN_abstract},
	{"add", FN_add},
	{"all", FN_all},
	{"aSCII", FN_aSCII},
	{"autoFlush", FN_autoFlush},
	{"bag", FN_bag},
	{"base", FN_base},
	{"bits", FN_bits},
	{"buf", FN_buf},
	{"c", FN_c},
	{"ch", FN_ch},
	{"char", FN_char},
	{"charset", FN_charset},
	{"class", FN_class},
	{"clear", FN_clear},
	{"close", FN_close},
	{"closed", FN_closed},
	{"cmd", FN_cmd},
	{"concat", FN_concat},
	{"const", FN_const},
	{"convert", FN_convert},
	{"copy", FN_copy},
	{"d", FN_d},
	{"data", FN_data},
	{"debug", FN_debug},
	{"decode", FN_decode},
	{"defined", FN_defined},
	{"delegate", FN_delegate},
	{"dump", FN_dump},
	{"e", FN_e},
	{"empty", FN_empty},
	{"enc", FN_enc},
	{"encode", FN_encode},
	{"end", FN_end},
	{"endsWith", FN_endsWith},
	{"equals", FN_equals},
	{"err", FN_err},
	{"event", FN_event},
	{"exec", FN_exec},
	{"f", FN_f},
	{"first", FN_first},
	{"flag", FN_flag},
	{"float", FN_float},
	{"flush", FN_flush},
	{"fmt", FN_fmt},
	{"format", FN_format},
	{"gc", FN_gc},
	{"hashCode", FN_hashCode},
	{"in", FN_in},
	{"indexOf", FN_indexOf},
	{"init", FN_init},
	{"initCapacity", FN_initCapacity},
	{"insert", FN_insert},
	{"int", FN_int},
	{"invoke", FN_invoke},
	{"it", FN_it},
	{"k", FN_k},
	{"key", FN_key},
	{"keys", FN_keys},
	{"lastIndexOf", FN_lastIndexOf},
	{"length", FN_length},
	{"listProperties", FN_listProperties},
	{"m", FN_m},
	{"main", FN_main},
	{"match", FN_match},
	{"method", FN_method},
	{"mode", FN_mode},
	{"mon", FN_mon},
	{"msg", FN_msg},
	{"n", FN_n},
	{"name", FN_name},
	{"new", FN_new},
	{"new:ARRAY", FN_new__ARRAY},
	{"new:LIST", FN_new__LIST},
	{"new:MAP", FN_new__MAP},
	{"new:TUPLE", FN_new__TUPLE},
	{"next", FN_next},
	{"notNull", FN_notNull},
	{"ns", FN_ns},
	{"null", FN_null},
	{"offset", FN_offset},
	{"option", FN_option},
	{"out", FN_out},
	{"path", FN_path},
	{"pattern", FN_pattern},
	{"pop", FN_pop},
	{"print", FN_print},
	{"println", FN_println},
	{"property", FN_property},
	{"putc", FN_putc},
	{"query", FN_query},
	{"random", FN_random},
	{"randomSeed", FN_randomSeed},
	{"re", FN_re},
	{"readLine", FN_readLine},
	{"readObject", FN_readObject},
	{"remove", FN_remove},
	{"replace", FN_replace},
	{"reqt", FN_reqt},
	{"reset", FN_reset},
	{"reverse", FN_reverse},
	{"s", FN_s},
	{"scheme", FN_scheme},
	{"search", FN_search},
	{"second", FN_second},
	{"seed", FN_seed},
	{"send", FN_send},
	{"shuffle", FN_shuffle},
	{"size", FN_size},
	{"split", FN_split},
	{"start", FN_start},
	{"startsWith", FN_startsWith},
	{"string", FN_string},
	{"substring", FN_substring},
	{"super", FN_super},
	{"swap", FN_swap},
	{"third", FN_third},
	{"this", FN_this},
	{"time", FN_time},
	{"trim", FN_trim},
	{"u", FN_u},
	{"urn", FN_urn},
	{"v", FN_v},
	{"value", FN_value},
	{"vargs", FN_vargs},
	{"w", FN_w},
	{"write", FN_write},
	{"writeASCII", FN_writeASCII},
	{"writeData", FN_writeData},
	{"writeObject", FN_writeObject},
	{"x", FN_x},
	{"y", FN_y},
	{"z", FN_z},
	{NULL}
};

static knh_data_t ParamArrayData0[] = {
	DATA_PARAM/*0*/, 0, 0, 0, 
	DATA_PARAM/*1*/, 0, 1, 1, TYPE_Int, FN_n, TYPE_T1, FN_return,
	DATA_PARAM/*2*/, 0, 2, 1, TYPE_Int, FN_x, TYPE_Int, FN_y, TYPE_T1, FN_return,
	DATA_PARAM/*3*/, 0, 3, 1, TYPE_Int, FN_x, TYPE_Int, FN_y, TYPE_Int, FN_z, TYPE_T1, FN_return,
	DATA_PARAM/*4*/, 0, 4, 1, TYPE_Int, FN_x, TYPE_Int, FN_y, TYPE_Int, FN_z, TYPE_Int, FN_w, TYPE_T1, FN_return,
	DATA_PARAM/*5*/, 0, 2, 1, TYPE_Int, FN_n, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*6*/, 0, 3, 1, TYPE_Int, FN_x, TYPE_Int, FN_y, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*7*/, 0, 4, 1, TYPE_Int, FN_x, TYPE_Int, FN_y, TYPE_Int, FN_z, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*8*/, 0, 5, 1, TYPE_Int, FN_x, TYPE_Int, FN_y, TYPE_Int, FN_z, TYPE_Int, FN_w, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*9*/, 0, 1, 1, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*10*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_T1, FN_value,
	DATA_PARAM/*11*/, 0, 2, 0, TYPE_Int, FN_n, TYPE_T1, FN_value,
	DATA_PARAM/*12*/, 0, 1, 0, TYPE_Int, FN_n,
	DATA_PARAM/*13*/, 0, 0, 1, TYPE_T1, FN_return,
	DATA_PARAM/*14*/, 0, 1, 1, TYPE_T1, FN_value, TYPE_Int, FN_return,
	DATA_PARAM/*15*/, 0, 2, 0, TYPE_Int, FN_m, TYPE_Int, FN_n,
	DATA_PARAM/*16*/, 0, 0, 1, TYPE_T1ITR, FN_return,
	DATA_PARAM/*17*/, 0, 1, 0, TYPE_Int, FN_char,
	DATA_PARAM/*18*/, 0, 3, 0, TYPE_BytesIm, FN_buf, TYPE_Int, FN_offset, TYPE_Int, FN_length,
	DATA_PARAM/*19*/, 0, 0, 1, TYPE_Class, FN_return,
	DATA_PARAM/*20*/, 0, 0, 1, TYPE_Int, FN_return,
	DATA_PARAM/*21*/, 0, 0, 1, TYPE_Boolean, FN_return,
	DATA_PARAM/*22*/, 0, 0, 1, TYPE_String, FN_return,
	DATA_PARAM/*23*/, 0, 0, 1, TYPE_This, FN_return,
	DATA_PARAM/*24*/, 0, 1, 1, TYPE_dynamic, FN_x, TYPE_dynamic, FN_return,
	DATA_PARAM/*25*/, 0, 1, 1, TYPE_T1, FN_key, TYPE_Boolean, FN_return,
	DATA_PARAM/*26*/, 0, 1, 1, TYPE_T1, FN_key, TYPE_T2, FN_return,
	DATA_PARAM/*27*/, 0, 2, 0, TYPE_T1, FN_key, TYPE_T2, FN_value,
	DATA_PARAM/*28*/, 0, 1, 0, TYPE_T1, FN_key,
	DATA_PARAM/*29*/, 0, 0, 1, TYPE_T1ARRAY, FN_return,
	DATA_PARAM/*30*/, 0, 1, 0, TYPE_Int, FN_seed,
	DATA_PARAM/*31*/, 0, 1, 1, TYPE_Int, FN_n, TYPE_Int, FN_return,
	DATA_PARAM/*32*/, 0, 0, 1, TYPE_Float, FN_return,
	DATA_PARAM/*33*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_dynamic, FN_value, TYPE_This, FN_return,
	DATA_PARAM/*34*/, 0, 1, 1, TYPE_Int, FN_init, TYPE_Bytes, FN_return,
	DATA_PARAM/*35*/, 0, 2, 1, TYPE_Bytes, FN_buf, TYPE_StringDecoder, FN_c, TYPE_String, FN_return,
	DATA_PARAM/*36*/, 0, 2, 1, TYPE_String, FN_pattern, TYPE_String, FN_option, TYPE_Regex, FN_return,
	DATA_PARAM/*37*/, 0, 2, 1, TYPE_T1, FN_start, TYPE_T1, FN_end, TYPE_This, FN_return,
	DATA_PARAM/*38*/, 0, 1, 1, TYPE_Int, FN_initCapacity, TYPE_This, FN_return,
	DATA_PARAM/*39*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_Int, FN_size, TYPE_This, FN_return,
	DATA_PARAM/*40*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_T1, FN_value, TYPE_This, FN_return,
	DATA_PARAM/*41*/, 0, 3, 1, TYPE_Int, FN_init, TYPE_String, FN_path, TYPE_NameSpace, FN_ns, TYPE_This, FN_return,
	DATA_PARAM/*42*/, 0, 3, 1, TYPE_String, FN_event, TYPE_String, FN_msg, TYPE_dynamic, FN_bag, TYPE_Exception, FN_return,
	DATA_PARAM/*43*/, 0, 2, 1, TYPE_dynamic, FN_base, TYPE_Method, FN_method, TYPE_This, FN_return,
	DATA_PARAM/*44*/, 0, 1, 1, TYPE_String, FN_msg, TYPE_Assurance, FN_return,
	DATA_PARAM/*45*/, 0, 1, 1, TYPE_Class, FN_c, TYPE_Boolean, FN_return,
	DATA_PARAM/*46*/, 0, 1, 1, TYPE_dynamic, FN_value, TYPE_Boolean, FN_return,
	DATA_PARAM/*47*/, 0, 1, 1, TYPE_Int, FN_value, TYPE_Boolean, FN_return,
	DATA_PARAM/*48*/, 0, 1, 1, TYPE_Float, FN_value, TYPE_Boolean, FN_return,
	DATA_PARAM/*49*/, 0, 1, 1, TYPE_String, FN_s, TYPE_Boolean, FN_return,
	DATA_PARAM/*50*/, 0, 1, 1, TYPE_dynamic, FN_v, TYPE_Boolean, FN_return,
	DATA_PARAM/*51*/, 0, 1, 1, TYPE_Int, FN_v, TYPE_Int, FN_return,
	DATA_PARAM/*52*/, 0, 1, 1, TYPE_Float, FN_v, TYPE_Float, FN_return,
	DATA_PARAM/*53*/, 0, 1, 1, TYPE_Float, FN_n, TYPE_Float, FN_return,
	DATA_PARAM/*54*/, 0, 1, 1, TYPE_String, FN_s, TYPE_String, FN_return,
	DATA_PARAM/*55*/, 0, 1, 1, TYPE_dynamic, FN_value, TYPE_dynamic, FN_return,
	DATA_PARAM/*56*/, 0, 0, 1, TYPE_dynamic, FN_return,
	DATA_PARAM/*57*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_Int, FN_n, TYPE_Int, FN_return,
	DATA_PARAM/*58*/, 0, 2, 1, TYPE_Int, FN_n, TYPE_Int, FN_c, TYPE_Int, FN_return,
	DATA_PARAM/*59*/, 0, 1, 0, TYPE_Int, FN_c,
	DATA_PARAM/*60*/, 0, 1, 1, TYPE_Int, FN_n, TYPE_String, FN_return,
	DATA_PARAM/*61*/, 0, 2, 1, TYPE_Int, FN_s, TYPE_Int, FN_e, TYPE_Bytes, FN_return,
	DATA_PARAM/*62*/, 0, 2, 1, TYPE_Int, FN_offset, TYPE_Int, FN_length, TYPE_String, FN_return,
	DATA_PARAM/*63*/, 0, 2, 1, TYPE_Int, FN_s, TYPE_Int, FN_e, TYPE_String, FN_return,
	DATA_PARAM/*64*/, 0, 2, 1, TYPE_Int, FN_s, TYPE_Int, FN_e, TYPE_This, FN_return,
	DATA_PARAM/*65*/, 0, 3, 1, TYPE_String, FN_urn, TYPE_NameSpace, FN_ns, TYPE_Monitor, FN_mon, TYPE_This, FN_return,
	DATA_PARAM/*66*/, 0, 1, 1, TYPE_String, FN_query, TYPE_ResultSet, FN_return,
	DATA_PARAM/*67*/, 0, 1, 0, TYPE_String, FN_query,
	DATA_PARAM/*68*/, 0, 1, 1, TYPE_dynamic, FN_n, TYPE_Int, FN_return,
	DATA_PARAM/*69*/, 0, 1, 1, TYPE_dynamic, FN_n, TYPE_Float, FN_return,
	DATA_PARAM/*70*/, 0, 1, 1, TYPE_dynamic, FN_n, TYPE_String, FN_return,
	DATA_PARAM/*71*/, 0, 1, 1, TYPE_dynamic, FN_n, TYPE_dynamic, FN_return,
	DATA_PARAM/*72*/, 0, 4, 1, TYPE_String, FN_urn, TYPE_String, FN_mode, TYPE_NameSpace, FN_ns, TYPE_Monitor, FN_mon, TYPE_InputStream, FN_return,
	DATA_PARAM/*73*/, 0, 1, 1, TYPE_StringDecoder, FN_c, TYPE_StringDecoder, FN_return,
	DATA_PARAM/*74*/, 0, 4, 1, TYPE_String, FN_urn, TYPE_String, FN_mode, TYPE_NameSpace, FN_ns, TYPE_Monitor, FN_mon, TYPE_OutputStream, FN_return,
	DATA_PARAM/*75*/, 0, 1, 0, TYPE_Int, FN_ch,
	DATA_PARAM/*76*/, 0, 3, 0, TYPE_Bytes, FN_buf, TYPE_Int, FN_offset, TYPE_Int, FN_length,
	DATA_PARAM/*77*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_Object, FN_value,
	DATA_PARAM/*78*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_dynamic, FN_value,
	DATA_PARAM/*79*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_String, FN_s,
	DATA_PARAM/*80*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_Object, FN_data,
	DATA_PARAM/*81*/, 0, 2, 0, TYPE_Object, FN_data, TYPE_NameSpace, FN_ns,
	DATA_PARAM/*82*/, 0, 2, 1, TYPE_Class, FN_c, TYPE_NameSpace, FN_ns, TYPE_dyn, FN_return,
	DATA_PARAM/*83*/, 0, 1, 1, TYPE_StringEncoder, FN_c, TYPE_StringEncoder, FN_return,
	DATA_PARAM/*84*/, 0, 1, 1, TYPE_String, FN_fmt, TYPE_String, FN_return,
	DATA_PARAM/*85*/, 0, 1, 1, TYPE_NameSpace, FN_ns, TYPE_Boolean, FN_return,
	DATA_PARAM/*86*/, 0, 3, 1, TYPE_String, FN_scheme, TYPE_NameSpace, FN_ns, TYPE_Class, FN_c, TYPE_dynamic, FN_return,
	DATA_PARAM/*87*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_Object, FN_value, TYPE_String, FN_return,
	DATA_PARAM/*88*/, 0, 1, 1, TYPE_dynamic, FN_value, TYPE_String, FN_return,
	DATA_PARAM/*89*/, 0, 1, 1, TYPE_String, FN_s, TYPE_Int, FN_return,
	DATA_PARAM/*90*/, 0, 1, 1, TYPE_Regex, FN_re, TYPE_Int, FN_return,
	DATA_PARAM/*91*/, 0, 1, 1, TYPE_Regex, FN_re, TYPE_StringARRAY, FN_return,
	DATA_PARAM/*92*/, 0, 2, 1, TYPE_Regex, FN_re, TYPE_String, FN_s, TYPE_String, FN_return,
	DATA_PARAM/*93*/, 0, 1, 1, TYPE_Converter, FN_enc, TYPE_Bytes, FN_return,
	DATA_PARAM/*94*/, 0, 1, 1, TYPE_StringEncoder, FN_enc, TYPE_Bytes, FN_return,
	DATA_PARAM/*95*/, 0, 1, 1, TYPE_StringDecoder, FN_c, TYPE_String, FN_return,
	DATA_PARAM/*96*/, 0, 1, 1, TYPE_StringConverter, FN_c, TYPE_String, FN_return,
	DATA_PARAM/*97*/, 0, 0, 1, TYPE_StringITR, FN_return,
	DATA_PARAM/*98*/, 0, 0, 1, TYPE_InputStream, FN_return,
	DATA_PARAM/*99*/, 0, 0, 1, TYPE_OutputStream, FN_return,
	DATA_PARAM/*100*/, 0, 1, 1, TYPE_String, FN_key, TYPE_dynamic, FN_return,
	DATA_PARAM/*101*/, 0, 2, 1, TYPE_String, FN_key, TYPE_dynamic, FN_value, TYPE_dynamic, FN_return,
	DATA_PARAM/*102*/, 0, 1, 1, TYPE_String, FN_key, TYPE_StringARRAY, FN_return,
	DATA_PARAM/*103*/, 0, 1, 1, TYPE_InputStream, FN_in, TYPE_InputStream, FN_return,
	DATA_PARAM/*104*/, 0, 1, 1, TYPE_OutputStream, FN_out, TYPE_OutputStream, FN_return,
	DATA_PARAM/*105*/, 0, 1, 1, TYPE_String, FN_event, TYPE_Boolean, FN_return,
	DATA_PARAM/*106*/, 0, 2, 1, TYPE_String, FN_name, TYPE_Object, FN_value, TYPE_dynamic, FN_return,
	DATA_PARAM/*107*/, 0, 2, 1, TYPE_String, FN_cmd, TYPE_Class, FN_reqt, TYPE_String, FN_return,
	DATA_PARAM/*108*/, 0, 1, 1, TYPE_Boolean, FN_flag, TYPE_Boolean, FN_return,
	0
};
#define K_PARAM0_SIZE                   109

static knh_data_t APIData0[] = {
	DATA_METHOD0, CLASS_Array, MN_get, 0, _DATA(Array_get), /*P=*/1,
	DATA_METHOD0, CLASS_ArrayIm, MN_get, 0, _DATA(Array_get), /*P=*/1,
	DATA_METHOD0, CLASS_Array, MN_get2, FLAG_Method_Hidden, _DATA(Array_get2), /*P=*/2,
	DATA_METHOD0, CLASS_ArrayIm, MN_get2, FLAG_Method_Hidden, _DATA(Array_get2), /*P=*/2,
	DATA_METHOD0, CLASS_Array, MN_get3, FLAG_Method_Hidden, _DATA(Array_get3), /*P=*/3,
	DATA_METHOD0, CLASS_ArrayIm, MN_get3, FLAG_Method_Hidden, _DATA(Array_get3), /*P=*/3,
	DATA_METHOD0, CLASS_Array, MN_get4, FLAG_Method_Hidden, _DATA(Array_get4), /*P=*/4,
	DATA_METHOD0, CLASS_ArrayIm, MN_get4, FLAG_Method_Hidden, _DATA(Array_get4), /*P=*/4,
	DATA_METHOD0, CLASS_Array, MN_set, 0, _DATA(Array_set), /*P=*/5,
	DATA_METHOD0, CLASS_Array, MN_set2, 0, _DATA(Array_set2), /*P=*/6,
	DATA_METHOD0, CLASS_Array, MN_set3, 0, _DATA(Array_set3), /*P=*/7,
	DATA_METHOD0, CLASS_Array, MN_set4, 0, _DATA(Array_set4), /*P=*/8,
	DATA_METHOD0, CLASS_Array, MN_setAll, 0, _DATA(Array_setAll), /*P=*/9,
	DATA_METHOD0, CLASS_Array, MN_add, 0, _DATA(Array_add), /*P=*/10,
	DATA_METHOD0, CLASS_Array, MN_send, 0, _DATA(Array_add), /*P=*/10,
	DATA_METHOD0, CLASS_Array, MN_insert, 0, _DATA(Array_insert), /*P=*/11,
	DATA_METHOD0, CLASS_Array, MN_clear, 0, _DATA(Array_clear), /*P=*/0,
	DATA_METHOD0, CLASS_Array, MN_remove, 0, _DATA(Array_remove), /*P=*/12,
	DATA_METHOD0, CLASS_Array, MN_pop, 0, _DATA(Array_pop), /*P=*/13,
	DATA_METHOD0, CLASS_Array, MN_indexOf, 0, _DATA(Array_indexOf), /*P=*/14,
	DATA_METHOD0, CLASS_Array, MN_lastIndexOf, 0, _DATA(Array_lastIndexOf), /*P=*/14,
	DATA_METHOD0, CLASS_Array, MN_swap, 0, _DATA(Array_swap), /*P=*/15,
	DATA_METHOD0, CLASS_Array, MN_shuffle, 0, _DATA(Array_shuffle), /*P=*/0,
	DATA_METHOD0, CLASS_Array, MN_reverse, 0, _DATA(Array_reverse), /*P=*/0,
	DATA_METHOD0, CLASS_Array, MN_opITR, 0, _DATA(Array_Iterator), /*P=*/16,
	DATA_METHOD0, CLASS_Bytes, MN_putc, 0, _DATA(Bytes_putc), /*P=*/17,
	DATA_METHOD0, CLASS_Bytes, MN_write, 0, _DATA(Bytes_write), /*P=*/18,
	DATA_METHOD0, CLASS_Bytes, MN_add, 0, _DATA(Bytes_write), /*P=*/18,
	DATA_METHOD0, CLASS_Object, MN_getClass, FLAG_Method_Const, _DATA(Object_getClass), /*P=*/19,
	DATA_METHOD0, CLASS_Object, MN_hashCode, 0, _DATA(Object_hashCode), /*P=*/20,
	DATA_METHOD0, CLASS_Object, MN_isNull, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_isNull), /*P=*/21,
	DATA_METHOD0, CLASS_Object, MN_isNotNull, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_isNotNull), /*P=*/21,
	DATA_METHOD0, CLASS_Object, MN_getKey, FLAG_Method_Const|FLAG_Method_Virtual, _DATA(Object_getKey), /*P=*/22,
	DATA_METHOD0, CLASS_Object, MN_copy, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_copy), /*P=*/23,
	DATA_METHOD0, CLASS_Method, MN_isAbstract, FLAG_Method_Const, _DATA(Method_isAbstract_), /*P=*/21,
	DATA_METHOD0, CLASS_Method, MN_getName, FLAG_Method_Const, _DATA(Method_getName), /*P=*/22,
	DATA_METHOD0, CLASS_Func, MN_invoke, FLAG_Method_Hidden|FLAG_Method_Private, _DATA(Func_invoke), /*P=*/24,
	DATA_METHOD0, CLASS_Map, MN_opHAS, 0, _DATA(Map_opHAS), /*P=*/25,
	DATA_METHOD0, CLASS_Map, MN_get, 0, _DATA(Map_get), /*P=*/26,
	DATA_METHOD0, CLASS_Map, MN_set, 0, _DATA(DictMap_set), /*P=*/27,
	DATA_METHOD0, CLASS_Map, MN_remove, 0, _DATA(DictMap_remove), /*P=*/28,
	DATA_METHOD0, CLASS_Map, MN_keys, 0, _DATA(Map_keys), /*P=*/29,
	DATA_METHOD0, CLASS_Map, MN_opITR, 0, _DATA(Map_T1__), /*P=*/16,
	DATA_METHOD0, CLASS_System, MN_setRandomSeed, FLAG_Method_Static, _DATA(System_setRandomSeed), /*P=*/30,
	DATA_METHOD0, CLASS_Int, MN_random, FLAG_Method_Static, _DATA(Int_random), /*P=*/31,
	DATA_METHOD0, CLASS_Float, MN_random, FLAG_Method_Static, _DATA(Float_random), /*P=*/32,
	DATA_METHOD0, CLASS_Int, MN__c, 0, _DATA(Int__c), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__u, 0, _DATA(Int__u), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__f, 0, _DATA(Int__f), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__x, 0, _DATA(Int__x), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__bits, 0, _DATA(Int__bits), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__d, 0, _DATA(Float__d), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__bits, 0, _DATA(Float__bits), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN_new, FLAG_Method_Virtual, _DATA(Object_new), /*P=*/23,
	DATA_METHOD0, CLASS_Object, MN_new__MAP, FLAG_Method_Hidden, _DATA(Object_newMAP), /*P=*/33,
	DATA_METHOD0, CLASS_Bytes, MN_new, 0, _DATA(Bytes_new), /*P=*/34,
	DATA_METHOD0, CLASS_Bytes, MN_new__ARRAY, 0, _DATA(Bytes_newARRAY), /*P=*/34,
	DATA_METHOD0, CLASS_String, MN_new, 0, _DATA(String_new), /*P=*/35,
	DATA_METHOD0, CLASS_Regex, MN_new, FLAG_Method_Const, _DATA(Regex_new), /*P=*/36,
	DATA_METHOD0, CLASS_Tuple, MN_new__TUPLE, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Tuple_newTUPLE), /*P=*/33,
	DATA_METHOD0, CLASS_Range, MN_new__LIST, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Range_newLIST), /*P=*/37,
	DATA_METHOD0, CLASS_Array, MN_new, 0, _DATA(Array_new), /*P=*/38,
	DATA_METHOD0, CLASS_Array, MN_new__ARRAY, FLAG_Method_Hidden, _DATA(Array_newARRAY), /*P=*/39,
	DATA_METHOD0, CLASS_Array, MN_new__LIST, FLAG_Method_Hidden, _DATA(Array_newLIST), /*P=*/40,
	DATA_METHOD0, CLASS_Map, MN_new, 0, _DATA(Map_new), /*P=*/41,
	DATA_METHOD0, CLASS_Map, MN_new__MAP, FLAG_Method_Hidden, _DATA(Map_newMAP), /*P=*/40,
	DATA_METHOD0, CLASS_Exception, MN_new, 0, _DATA(Exception_new), /*P=*/42,
	DATA_METHOD0, CLASS_Func, MN_new, 0, _DATA(Func_new), /*P=*/43,
	DATA_METHOD0, CLASS_Assurance, MN_new, FLAG_Method_Const, _DATA(Assurance_new), /*P=*/44,
	DATA_METHOD0, CLASS_Object, MN_opADDR, FLAG_Method_Const, _DATA(Object_opADDR), /*P=*/20,
	DATA_METHOD0, CLASS_Object, MN_opOF, FLAG_Method_Const, _DATA(Object_opOF), /*P=*/45,
	DATA_METHOD0, CLASS_Object, MN_opEQ, FLAG_Method_Const, _DATA(Object_opEQ), /*P=*/46,
	DATA_METHOD0, CLASS_Object, MN_opNOTEQ, FLAG_Method_Const, _DATA(Object_opNOTEQ), /*P=*/46,
	DATA_METHOD0, CLASS_Object, MN_opLT, FLAG_Method_Const, _DATA(Object_opLT), /*P=*/46,
	DATA_METHOD0, CLASS_Object, MN_opLTE, FLAG_Method_Const, _DATA(Object_opLTE), /*P=*/46,
	DATA_METHOD0, CLASS_Object, MN_opGT, FLAG_Method_Const, _DATA(Object_opGT), /*P=*/46,
	DATA_METHOD0, CLASS_Object, MN_opGTE, FLAG_Method_Const, _DATA(Object_opGTE), /*P=*/46,
	DATA_METHOD0, CLASS_Int, MN_opEQ, FLAG_Method_Const, _DATA(Int_opEQ), /*P=*/47,
	DATA_METHOD0, CLASS_Int, MN_opNOTEQ, FLAG_Method_Const, _DATA(Int_opNOTEQ), /*P=*/47,
	DATA_METHOD0, CLASS_Int, MN_opLT, FLAG_Method_Const, _DATA(Int_opLT), /*P=*/47,
	DATA_METHOD0, CLASS_Int, MN_opLTE, FLAG_Method_Const, _DATA(Int_opLTE), /*P=*/47,
	DATA_METHOD0, CLASS_Int, MN_opGT, FLAG_Method_Const, _DATA(Int_opGT), /*P=*/47,
	DATA_METHOD0, CLASS_Int, MN_opGTE, FLAG_Method_Const, _DATA(Int_opGTE), /*P=*/47,
	DATA_METHOD0, CLASS_Float, MN_opEQ, FLAG_Method_Const, _DATA(Float_opEQ), /*P=*/48,
	DATA_METHOD0, CLASS_Float, MN_opNOTEQ, FLAG_Method_Const, _DATA(Float_opNOTEQ), /*P=*/48,
	DATA_METHOD0, CLASS_Float, MN_opLT, FLAG_Method_Const, _DATA(Float_opLT), /*P=*/48,
	DATA_METHOD0, CLASS_Float, MN_opLTE, FLAG_Method_Const, _DATA(Float_opLTE), /*P=*/48,
	DATA_METHOD0, CLASS_Float, MN_opGT, FLAG_Method_Const, _DATA(Float_opGT), /*P=*/48,
	DATA_METHOD0, CLASS_Float, MN_opGTE, FLAG_Method_Const, _DATA(Float_opGTE), /*P=*/48,
	DATA_METHOD0, CLASS_String, MN_opHAS, FLAG_Method_Const, _DATA(String_opHAS), /*P=*/49,
	DATA_METHOD0, CLASS_Array, MN_opHAS, 0, _DATA(Array_opHAS), /*P=*/50,
	DATA_METHOD0, CLASS_Object, MN_opIS, FLAG_Method_Const, _DATA(Object_opIS), /*P=*/50,
	DATA_METHOD0, CLASS_Int, MN_opADD, FLAG_Method_Const, _DATA(Int_opADD), /*P=*/51,
	DATA_METHOD0, CLASS_Int, MN_opNEG, FLAG_Method_Const, _DATA(Int_opNEG), /*P=*/20,
	DATA_METHOD0, CLASS_Int, MN_opSUB, FLAG_Method_Const, _DATA(Int_opSUB), /*P=*/31,
	DATA_METHOD0, CLASS_Int, MN_opMUL, FLAG_Method_Const, _DATA(Int_opMUL), /*P=*/31,
	DATA_METHOD0, CLASS_Int, MN_opDIV, FLAG_Method_Const, _DATA(Int_opDIV), /*P=*/31,
	DATA_METHOD0, CLASS_Int, MN_opMOD, FLAG_Method_Const, _DATA(Int_opMOD), /*P=*/31,
	DATA_METHOD0, CLASS_Float, MN_opADD, FLAG_Method_Const, _DATA(Float_opADD), /*P=*/52,
	DATA_METHOD0, CLASS_Float, MN_opNEG, FLAG_Method_Const, _DATA(Float_opNEG), /*P=*/32,
	DATA_METHOD0, CLASS_Float, MN_opSUB, FLAG_Method_Const, _DATA(Float_opSUB), /*P=*/53,
	DATA_METHOD0, CLASS_Float, MN_opMUL, FLAG_Method_Const, _DATA(Float_opMUL), /*P=*/53,
	DATA_METHOD0, CLASS_Float, MN_opDIV, FLAG_Method_Const, _DATA(Float_opDIV), /*P=*/53,
	DATA_METHOD0, CLASS_String, MN_opSUB, FLAG_Method_Const, _DATA(String_opSUB), /*P=*/54,
	DATA_METHOD0, CLASS_dynamic, MN_opADD, 0, _DATA(dynamic_opADD), /*P=*/55,
	DATA_METHOD0, CLASS_dynamic, MN_opSUB, 0, _DATA(dynamic_opADD), /*P=*/55,
	DATA_METHOD0, CLASS_dynamic, MN_opMUL, 0, _DATA(dynamic_opADD), /*P=*/55,
	DATA_METHOD0, CLASS_dynamic, MN_opDIV, 0, _DATA(dynamic_opADD), /*P=*/55,
	DATA_METHOD0, CLASS_dynamic, MN_opMOD, 0, _DATA(dynamic_opADD), /*P=*/55,
	DATA_METHOD0, CLASS_dynamic, MN_opNEG, 0, _DATA(dynamic_opADD), /*P=*/56,
	DATA_METHOD0, CLASS_Boolean, MN_opNOT, FLAG_Method_Const, _DATA(Boolean_opNOT), /*P=*/21,
	DATA_METHOD0, CLASS_Int, MN_opLAND, FLAG_Method_Const, _DATA(Int_opLAND), /*P=*/57,
	DATA_METHOD0, CLASS_Int, MN_opLOR, FLAG_Method_Const, _DATA(Int_opLOR), /*P=*/57,
	DATA_METHOD0, CLASS_Int, MN_opLXOR, FLAG_Method_Const, _DATA(Int_opLXOR), /*P=*/31,
	DATA_METHOD0, CLASS_Int, MN_opLNOT, FLAG_Method_Const, _DATA(Int_opLNOT), /*P=*/20,
	DATA_METHOD0, CLASS_Int, MN_opLSFT, FLAG_Method_Const, _DATA(Int_opLSFT), /*P=*/31,
	DATA_METHOD0, CLASS_Int, MN_opRSFT, FLAG_Method_Const, _DATA(Int_opRSFT), /*P=*/31,
	DATA_METHOD0, CLASS_Bytes, MN_getSize, 0, _DATA(Bytes_getSize), /*P=*/20,
	DATA_METHOD0, CLASS_Array, MN_getSize, 0, _DATA(Bytes_getSize), /*P=*/20,
	DATA_METHOD0, CLASS_Tuple, MN_getSize, 0, _DATA(Tuple_getSize), /*P=*/20,
	DATA_METHOD0, CLASS_String, MN_getSize, FLAG_Method_Const, _DATA(String_getSize), /*P=*/20,
	DATA_METHOD0, CLASS_Map, MN_getSize, 0, _DATA(Map_getSize), /*P=*/20,
	DATA_METHOD0, CLASS_Bytes, MN_get, 0, _DATA(Bytes_get), /*P=*/31,
	DATA_METHOD0, CLASS_Bytes, MN_set, 0, _DATA(Bytes_set), /*P=*/58,
	DATA_METHOD0, CLASS_Bytes, MN_setAll, 0, _DATA(Bytes_setAll), /*P=*/59,
	DATA_METHOD0, CLASS_String, MN_get, FLAG_Method_Const, _DATA(String_get), /*P=*/60,
	DATA_METHOD0, CLASS_Bytes, MN_opUNTIL, 0, _DATA(Bytes_opUNTIL), /*P=*/61,
	DATA_METHOD0, CLASS_Bytes, MN_opTO, 0, _DATA(Bytes_opTO), /*P=*/61,
	DATA_METHOD0, CLASS_String, MN_substring, FLAG_Method_Const, _DATA(String_substring), /*P=*/62,
	DATA_METHOD0, CLASS_String, MN_opUNTIL, FLAG_Method_Const, _DATA(String_opUNTIL), /*P=*/63,
	DATA_METHOD0, CLASS_String, MN_opTO, FLAG_Method_Const, _DATA(String_opTO), /*P=*/63,
	DATA_METHOD0, CLASS_Array, MN_opUNTIL, 0, _DATA(Array_opUNTIL), /*P=*/64,
	DATA_METHOD0, CLASS_Array, MN_opTO, 0, _DATA(Array_opTO), /*P=*/64,
	DATA_METHOD0, CLASS_Connection, MN_new, 0, _DATA(Connection_new), /*P=*/65,
	DATA_METHOD0, CLASS_Connection, MN_query, 0, _DATA(Connection_query), /*P=*/66,
	DATA_METHOD0, CLASS_Connection, MN_exec, 0, _DATA(Connection_exec), /*P=*/67,
	DATA_METHOD0, CLASS_Connection, MN_close, 0, _DATA(Connection_close), /*P=*/0,
	DATA_METHOD0, CLASS_ResultSet, MN_getSize, 0, _DATA(ResultSet_getSize), /*P=*/20,
	DATA_METHOD0, CLASS_ResultSet, MN_next, 0, _DATA(ResultSet_next), /*P=*/21,
	DATA_METHOD0, CLASS_ResultSet, MN_getName, 0, _DATA(ResultSet_getName), /*P=*/60,
	DATA_METHOD0, CLASS_ResultSet, MN_getInt, 0, _DATA(ResultSet_getInt), /*P=*/68,
	DATA_METHOD0, CLASS_ResultSet, MN_getFloat, 0, _DATA(ResultSet_getFloat), /*P=*/69,
	DATA_METHOD0, CLASS_ResultSet, MN_getString, 0, _DATA(ResultSet_getString), /*P=*/70,
	DATA_METHOD0, CLASS_ResultSet, MN_get, 0, _DATA(ResultSet_get), /*P=*/71,
	DATA_METHOD0, CLASS_ResultSet, MN_close, 0, _DATA(ResultSet_close), /*P=*/0,
	DATA_METHOD0, CLASS_InputStream, MN_new, 0, _DATA(InputStream_new), /*P=*/72,
	DATA_METHOD0, CLASS_InputStream, MN_getChar, 0, _DATA(InputStream_getChar), /*P=*/20,
	DATA_METHOD0, CLASS_InputStream, MN_isClosed, 0, _DATA(InputStream_isClosed_), /*P=*/21,
	DATA_METHOD0, CLASS_InputStream, MN_close, 0, _DATA(InputStream_close), /*P=*/0,
	DATA_METHOD0, CLASS_InputStream, MN_setCharset, 0, _DATA(InputStream_setCharset_), /*P=*/73,
	DATA_METHOD0, CLASS_InputStream, MN_readLine, 0, _DATA(InputStream_readLine), /*P=*/22,
	DATA_METHOD0, CLASS_OutputStream, MN_new, 0, _DATA(OutputStream_new), /*P=*/74,
	DATA_METHOD0, CLASS_OutputStream, MN_writeASCII, 0, _DATA(OutputStream_writeASCII), /*P=*/75,
	DATA_METHOD0, CLASS_OutputStream, MN_write, 0, _DATA(OutputStream_write), /*P=*/76,
	DATA_METHOD0, CLASS_OutputStream, MN_isClosed, 0, _DATA(OutputStream_isClosed_), /*P=*/21,
	DATA_METHOD0, CLASS_OutputStream, MN_print, 0, _DATA(OutputStream_print), /*P=*/77,
	DATA_METHOD0, CLASS_OutputStream, MN_println, 0, _DATA(OutputStream_println), /*P=*/78,
	DATA_METHOD0, CLASS_OutputStream, MN_send, 0, _DATA(OutputStream_send), /*P=*/79,
	DATA_METHOD0, CLASS_OutputStream, MN_writeData, 0, _DATA(*knh_getPackSPI), /*P=*/80,
	DATA_METHOD0, CLASS_OutputStream, MN_writeObject, 0, _DATA(OutputStream_writeObject), /*P=*/81,
	DATA_METHOD0, CLASS_InputStream, MN_readObject, 0, _DATA(InputStream_readObject), /*P=*/82,
	DATA_METHOD0, CLASS_OutputStream, MN_flush, 0, _DATA(OutputStream_flush), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_reset, 0, _DATA(OutputStream_reset), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_close, 0, _DATA(OutputStream_close), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_setCharset, 0, _DATA(OutputStream_setCharaset), /*P=*/83,
	DATA_METHOD0, CLASS_Int, MN_format, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Int_format), /*P=*/84,
	DATA_METHOD0, CLASS_Float, MN_format, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Float_format), /*P=*/84,
	DATA_METHOD0, CLASS_String, MN_format, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(String_format), /*P=*/84,
	DATA_METHOD0, CLASS_Object, MN__empty, 0, _DATA(Object__empty), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__s, 0, _DATA(Object__s), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__k, 0, _DATA(Object__k), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__data, 0, _DATA(Object__data), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__dump, 0, _DATA(Object__dump), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__s, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__k, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__data, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__dump, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__s, 0, _DATA(Int__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__d, 0, _DATA(Int__s), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__s, 0, _DATA(Float__s), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__f, 0, _DATA(Float__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__k, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__data, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__dump, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__k, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__data, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__dump, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_String, MN_opEXISTS, FLAG_Method_Const, _DATA(String_opEXISTS), /*P=*/85,
	DATA_METHOD0, CLASS_String, MN_path, FLAG_Method_Hidden|FLAG_Method_Private, _DATA(String_path), /*P=*/86,
	DATA_METHOD0, CLASS_String, MN_equals, FLAG_Method_Const, _DATA(String_equals), /*P=*/49,
	DATA_METHOD0, CLASS_String, MN_startsWith, FLAG_Method_Const, _DATA(String_startsWith), /*P=*/49,
	DATA_METHOD0, CLASS_String, MN_endsWith, FLAG_Method_Const, _DATA(String_endsWith), /*P=*/49,
	DATA_METHOD0, CLASS_String, MN_concat, FLAG_Method_Const, _DATA(String_concat), /*P=*/87,
	DATA_METHOD0, CLASS_String, MN_opADD, FLAG_Method_Const, _DATA(String_concat), /*P=*/88,
	DATA_METHOD0, CLASS_String, MN_indexOf, FLAG_Method_Const, _DATA(String_indexOf), /*P=*/89,
	DATA_METHOD0, CLASS_String, MN_lastIndexOf, FLAG_Method_Const, _DATA(String_lastIndexOf), /*P=*/89,
	DATA_METHOD0, CLASS_String, MN_search, FLAG_Method_Const, _DATA(String_search), /*P=*/90,
	DATA_METHOD0, CLASS_String, MN_match, FLAG_Method_Const, _DATA(String_match), /*P=*/91,
	DATA_METHOD0, CLASS_String, MN_replace, FLAG_Method_Const, _DATA(String_replace), /*P=*/92,
	DATA_METHOD0, CLASS_String, MN_split, FLAG_Method_Const, _DATA(String_split), /*P=*/91,
	DATA_METHOD0, CLASS_Bytes, MN_, FLAG_Method_Const, _DATA(Bytes_convert), /*P=*/93,
	DATA_METHOD0, CLASS_String, MN_encode, FLAG_Method_Const, _DATA(String_encode), /*P=*/94,
	DATA_METHOD0, CLASS_Bytes, MN_decode, FLAG_Method_Const, _DATA(Bytes_toString), /*P=*/95,
	DATA_METHOD0, CLASS_String, MN_, FLAG_Method_Const, _DATA(String_convert), /*P=*/96,
	DATA_METHOD0, CLASS_String, MN_convert, FLAG_Method_Const, _DATA(String_convert), /*P=*/96,
	DATA_METHOD0, CLASS_String, MN_trim, FLAG_Method_Const, _DATA(String_trim), /*P=*/22,
	DATA_METHOD0, CLASS_Regex, MN_opHAS, FLAG_Method_Const, _DATA(Regex_opHAS), /*P=*/49,
	DATA_METHOD0, CLASS_String, MN_opITR, 0, _DATA(String_Iterator), /*P=*/97,
	DATA_METHOD0, CLASS_System, MN_getIn, FLAG_Method_Static, _DATA(System_getIn), /*P=*/98,
	DATA_METHOD0, CLASS_System, MN_getOut, FLAG_Method_Static, _DATA(System_getOut), /*P=*/99,
	DATA_METHOD0, CLASS_System, MN_getErr, FLAG_Method_Static, _DATA(System_getErr), /*P=*/99,
	DATA_METHOD0, CLASS_System, MN_getProperty, FLAG_Method_Static, _DATA(System_getProperty), /*P=*/100,
	DATA_METHOD0, CLASS_System, MN_setProperty, FLAG_Method_Static, _DATA(System_setProperty), /*P=*/101,
	DATA_METHOD0, CLASS_System, MN_listProperties, FLAG_Method_Hidden, _DATA(System_listProperties), /*P=*/102,
	DATA_METHOD0, CLASS_System, MN_gc, FLAG_Method_Static, _DATA(System_gc), /*P=*/0,
	DATA_METHOD0, CLASS_System, MN_getTime, 0, _DATA(System_getTime), /*P=*/20,
	DATA_METHOD0, CLASS_Context, MN_setIn, FLAG_Method_Static, _DATA(CTX_setIn), /*P=*/103,
	DATA_METHOD0, CLASS_Context, MN_setOut, FLAG_Method_Static, _DATA(CTX_setOut), /*P=*/104,
	DATA_METHOD0, CLASS_Context, MN_setErr, FLAG_Method_Static, _DATA(CTX_setErr), /*P=*/104,
	DATA_METHOD0, CLASS_Exception, MN_opOF, 0, _DATA(Exception_opOF), /*P=*/105,
	DATA_METHOD0, CLASS_Class, MN_setConst, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Class_setConst), /*P=*/106,
	DATA_METHOD0, CLASS_System, MN_exec, FLAG_Method_Static, _DATA(System_exec), /*P=*/107,
	DATA_METHOD0, CLASS_String, MN_isASCII, 0, _DATA(_String_isASCII), /*P=*/21,
	DATA_METHOD0, CLASS_OutputStream, MN_isAutoFlush, 0, _DATA(_OutputStream_isAutoFlush), /*P=*/21,
	DATA_METHOD0, CLASS_OutputStream, MN_setAutoFlush, 0, _DATA(_OutputStream_setAutoFlush), /*P=*/108,
	DATA_METHOD0, CLASS_Context, MN_isDebug, 0, _DATA(_Context_isDebug), /*P=*/21,
	DATA_METHOD0, CLASS_Context, MN_setDebug, 0, _DATA(_Context_setDebug), /*P=*/108,
	DATA_TYPEMAP, CLASS_Iterator, CLASS_Iterator, 0, _DATA(Iterator_Iterator),
	DATA_TYPEMAP, CLASS_Array, CLASS_Array, 0, _DATA(Array_Array),
	DATA_TYPEMAP, CLASS_Iterator, CLASS_Array, 0, _DATA(Iterator_Array),
	DATA_TYPEMAP, CLASS_Array, CLASS_Iterator, 0, _DATA(Array_Iterator),
	DATA_TYPEMAP, CLASS_Map, CLASS_Iterator, 0, _DATA(Map_T1__),
	DATA_TYPEMAP, CLASS_Map, CLASS_T1ITR, 0, _DATA(Map_T1__),
	DATA_TYPEMAP, CLASS_Boolean, CLASS_Object, FLAG_TypeMap_Const, _DATA(Boolean_Object),
	DATA_TYPEMAP, CLASS_Boolean, CLASS_Tdynamic, FLAG_TypeMap_Const, _DATA(Boolean_Object),
	DATA_TYPEMAP, CLASS_Int, CLASS_Object, FLAG_TypeMap_Const, _DATA(Int_Object),
	DATA_TYPEMAP, CLASS_Int, CLASS_Number, FLAG_TypeMap_Const, _DATA(Int_Object),
	DATA_TYPEMAP, CLASS_Int, CLASS_Tdynamic, FLAG_TypeMap_Const, _DATA(Int_Object),
	DATA_TYPEMAP, CLASS_Float, CLASS_Object, FLAG_TypeMap_Const, _DATA(Float_Object),
	DATA_TYPEMAP, CLASS_Float, CLASS_Number, FLAG_TypeMap_Const, _DATA(Float_Object),
	DATA_TYPEMAP, CLASS_Float, CLASS_Tdynamic, FLAG_TypeMap_Const, _DATA(Float_Object),
	DATA_TYPEMAP, CLASS_Boolean, CLASS_String, FLAG_TypeMap_Const, _DATA(Boolean_String),
	DATA_TYPEMAP, CLASS_Int, CLASS_String, FLAG_TypeMap_Const, _DATA(Int_String),
	DATA_TYPEMAP, CLASS_Float, CLASS_String, FLAG_TypeMap_Const, _DATA(Float_String),
	DATA_TYPEMAP, CLASS_Float, CLASS_Int, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(Float_Int),
	DATA_TYPEMAP, CLASS_Int, CLASS_Float, FLAG_TypeMap_Const|FLAG_TypeMap_Semantic, _DATA(Int_Float),
	DATA_TYPEMAP, CLASS_String, CLASS_Regex, FLAG_TypeMap_Const, _DATA(String_Regex),
	DATA_TYPEMAP, CLASS_InputStream, CLASS_StringITR, 0, _DATA(knh_InputStream_String__),
	DATA_TYPEMAP, CLASS_String, CLASS_Int, FLAG_TypeMap_Const, _DATA(String_Int),
	DATA_TYPEMAP, CLASS_String, CLASS_Float, FLAG_TypeMap_Const, _DATA(String_Float),
	DATA_TYPEMAP, CLASS_String, CLASS_Bytes, FLAG_TypeMap_Const, _DATA(String_Bytes),
	DATA_TYPEMAP, CLASS_String, CLASS_StringITR, FLAG_TypeMap_Const, _DATA(String_Iterator),
	DATA_TYPEMAP, CLASS_Bytes, CLASS_InputStream, 0, _DATA(Bytes_InputStream),
	0
};
