######################################################################
# Automatically generated by qmake (2.01a) ? 5? 17 18:36:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Widget.h Window.h
SOURCES += main.cpp MainWindow.cpp Widget.cpp
