######################################################################
# Automatically generated by qmake (2.01a) ? 5? 12 00:45:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += file_read.h Widget.h Window.h
SOURCES += file_read.cpp main.cpp MainWindow.cpp Widget.cpp
