#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
 doc.cgi : switch index html
 copyright (c) chen_ji 2011
'''

import Cookie
import os
import login
import aspendb
import datetime
import ConfigParser

html = '''<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<title>Aspen - An online KonohaScript editor</title>

		<!-- for IE compatibility -->
		<!--[if lt IE 9]>
		<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
		<![endif]-->

		<!-- codemirror -->
		<script src="%(p)sjs/codemirror.js"></script>
		<script src="%(p)sjs/autocompletion.js"></script>
		<link rel="stylesheet" href="%(p)scss/codemirror.css">

		<!-- syntax highlight -->
		<script src="%(p)sjs/konoha.js"></script>
		<link rel="stylesheet" href="%(p)scss/konoha.css">

		<!-- mootools -->
		<script src="%(p)sjs/mootools-core-1.3.2-full-compat.js"></script>
		<script src="%(p)sjs/mootools-more-1.3.2.1.js"></script>

		<!-- aspen -->
		<script src="%(p)sjs/aspen.js"></script>
		<link rel="stylesheet" href="%(p)scss/aspen.css">
	</head>
	<body>
		<!-- header menu -->
		<header>
			<div id="topmenu_l">
				<div class="menubutton" id="new">New</div>
				<div class="menubutton" id="eval">Run</div>
			</div>
			<div id="topmenu_r">
				<img src="http://img.tweetimag.es/i/%(user)s_m" alt="%(user)s"
				align="top" />
				<div class="userinfo" id="user">%(user)s</div>
				<div class="menubutton" id="sign_out">Sign out</div>
			</div>
		</header>

		<!-- result -->
		<div id="result">
			<span class="message"></span>
		</div>

		<!-- editor body -->
		<textarea id="code" name="code"></textarea>
	</body>
</html>'''

def redirect():
	lm = login.LoginManager()
	rtoken = lm.getRequestToken()
	lm.saveRequestCookie(rtoken)
	lm.redirectToProvider(rtoken['oauth_token'])

def main():
	cookie = Cookie.SimpleCookie(os.environ.get('HTTP_COOKIE', ''))
	if cookie.has_key('SID'):
		astorage = aspendb.AspenStorage()
		name = astorage.getScreenName(cookie['SID'].value)
		if name != None:
			conf = ConfigParser.SafeConfigParser()
			conf.read('settings.ini')
			print 'Content-Type: text/html\n'
			print (html % {'p': conf.get('path', 'base'), 'user': name})
		else:
			# remove cookie SID
			cookie['SID']['expires'] = datetime.datetime.now() + \
				datetime.timedelta(days=-1)
			cookie['SID']['path'] = '/'
			print cookie
			redirect()
	else:
		redirect()

if __name__ == '__main__':
	main()
