######################################################################
# Automatically generated by qmake (2.01a) ? 5? 17 18:00:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += file_read.h
SOURCES += file_read.cpp main.cpp
